# Generated by Django 2.2 on 2019-04-26 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RunArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RunPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.BigIntegerField()),
                ('duration', models.BigIntegerField(null=True)),
                ('elevation_gain', models.IntegerField(null=True)),
                ('elevation_loss', models.IntegerField(null=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('id_name', models.CharField(max_length=100, null=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_paths', to='runner_api_backend.Cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('altitude', models.DecimalField(decimal_places=16, max_digits=20, null=True)),
                ('distance', models.BigIntegerField()),
                ('elevation_gain', models.IntegerField(null=True)),
                ('elevation_loss', models.IntegerField(null=True)),
                ('run_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='runner_api_backend.RunPath')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='runner_api_backend.RunArea'),
        ),
    ]
