# Generated by Django 2.2.1 on 2019-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='distance',
            field=models.BigIntegerField(null=True),
        ),
    ]
